### ISSUE TITLE
issue : bar 크기 확장시 이어짐 문제 재발

### ISSUE THREAD

**Issue by codusl100** [codusl100/gantt_scheduling#9]

**Comment by seulgigi** [comment]
수정 전: progressbar_position이 움직인 후 bar_position, label_position, arrow_position이 움직임

> progressbar_position이 update 될 때마다 나머지 position도 update 되도록 코드 수정
```
this.update_attr(bar, 'x', x);
// add bar_progress position
this.update_attr(bar_progress, 'x', x);
// add label position
this.update_label_position();
// add arrow position
this.update_arrow_position();
```
위를 `this.update_attr(bar, 'x', x);` 혹은 `this.update_attr(bar, 'width', width);`가 나올 때 동시 선언
